DEPT-33 site topics listing
dof-dss/nicsdru_dept pull request #146
Opened 2022-06-29 14:20 UTC by johangant

Omitting the D7 approach of draggableviews, because we already have entity queue module and this provides a perfect basis for defining and structuring lists of arbitrarily ordered content.

- We have one topics queue per group - naming is based on `<site_id>_topics` pattern.
- There's some preprocess code to adjust the view's query join condition so it selects the correct queue based on the active department.

2022-06-29 14:53 UTC, johangant commented
Need to populate the entity queues once config has imported. That content isn't exportable, sadly.

2022-06-30 08:54 UTC, omahm requested changes
Looks solid, just one wee niggle around the topic naming.

2022-06-30 11:39 UTC, johangant commented on config/sync/entityqueue.entity_queue.department_of_finance_topics.yml
> +label: 'Department of Finance topics'
Yep, that seems reasonable to me. Will adjust the config and push up the changes.

2022-07-01 08:21 UTC, omahm approved these changes

2022-07-01 08:22 UTC, merged