DEPT-265 ~ Config split for development domain hostnames
dof-dss/nicsdru_dept pull request #267
Opened 2022-11-23 11:58 UTC by omahm

2022-11-23 12:38 UTC, johangant requested changes
LGTM, just needs a tweak for the protocol/scheme for some domain records.

2022-11-23 13:56 UTC, omahm commented on config/development/domain.record.group_9.yml
> +scheme: variable
The hostname doesn't have a protocol, see https://github.com/dof-dss/nicsdru_dept/blob/development/config/sync/domain.record.group_1.yml

2022-11-25 14:40 UTC, johangant commented on config/development/domain.record.group_9.yml
> +scheme: variable
Sorry, meant the `scheme` which is sometimes set to `variable`. Changing `variable` to the value of `https` (or vice versa) across all domain records would keep it consistent.

2022-11-28 09:12 UTC, omahm commented on config/development/domain.record.group_9.yml
> +scheme: variable
That's a good point, hadn't spotted that.

2022-11-28 13:50 UTC, merged