Fix topics display modes
dof-dss/nicsdru_dept pull request #333
Opened 2023-02-09 14:12 UTC by johangant

2023-02-09 14:47 UTC, johangant commented on web/modules/custom/dept_topics/src/Commands/DeptTopicsCommands.php
> +  private function domainD7ToD9(int $d7_id) {
Couldn't find something open/service related that did the same thing as this so popped it in here (for now) - should be easy to extract into a service (new or existing) if it's useful in multiple contexts

2023-02-10 11:44 UTC, omahm requested changes
Looks good overall but I'd maybe inject the db conn instead of calling Drupal::database each time in those for loops.

2023-02-10 11:44 UTC, omahm commented on web/modules/custom/dept_topics/src/Commands/DeptTopicsCommands.php
> +        \Drupal::database()->insert('draggableviews_structure')
I'd look at injecting the database connection as a service

2023-02-10 11:44 UTC, omahm commented on web/modules/custom/dept_topics/src/Commands/DeptTopicsCommands.php
> +        $existing_dv_data = \Drupal::database()
Inject this and the call further down as a service

2023-02-10 15:41 UTC, omahm approved these changes
LGTM 👍

2023-02-10 15:46 UTC, merged